os: linux
dist: trusty
sudo: required
language: ruby

before_install:
- sudo apt-get install -y pandoc rubber
- sudo apt-get install -y texlive-fonts-recommended texlive-fonts-extra
- sudo apt-get install -y texlive-latex-recommended texlive-latex-extra
- sudo apt-get install -y texlive-science texlive-pictures
- sudo apt-get install -y texlive-xetex
- sudo apt-get install -y pdftk

script:
- rubber --pdf main.tex
- pdftk main.pdf cat 1-2 output biosketch.pdf
- pdftk main.pdf cat 3-4 output collaborators.pdf
- pdftk main.pdf cat 5-end output bibliography.pdf

deploy:
  provider: releases
  api_key:
    secure: zWJsb8vXb0HRxvUYATNt4akOMn/8VXjUC+l6syfSb2LrHX+esRibAg9dgBjA/1Cn9pxM/jNXD6AC9d1GalU8Mh+g5xx+nhmZGNhz159lVkHwkE70dcJ7ZTQYN+WHp3iQudxGvBtTBLMqGJlhaWmBBUg0+wWBsZPm4bCKRWllzzOMHvHUFUD1ahPAC0DUpNKnUmSHbLeDbaibqoU/OKfDrpi7S6A2Blf3DycWm9ocIW/UUB7HK952HmLEJkFGIX5VHNBPCA0WFsXmLyPWW+Q5a7CeYPPpz3o5XGSscuCo8FCHXJBhLeQPVyY6JJFvJCSEcpKBQHRIeAztxkepSqM6g9rv8M+tc3LhmLZkb7b5bd8f+vLV+53F/mvw/tooZMcjdmCE+Pfh0pUQj9CMR1IsBJC9jUkd66AgKmx9nYrdwt41qnjiL+hizt4owMp7any3Z2cw9JqqfWZ7vl0yaHB/URhxyNKLKXbyeZtIEI8P3cKkiwdnZZSfPRcsXEWDZzJLDEzJCw7NtQ9GJPWRWdpIgrIYumYed0y3uDQxuBRek9UkDVSYpd5SKxpFGRRITYUKqi+bVomZTpAbcocNyydsRqUbxyMenZdXctJ3r5v+BLnt7sdjGO7+T+pUOsDk8XoHRwvI1XMPfV9IaKqIzPRf9IHQb06i2RdQqAc9F8DuLR8=
  file:
  - main.pdf
  - biosketch.pdf
  - collaborators.pdf
  - bibliography.pdf
  skip_cleanup: true
  on:
    repo: wdconinc/biosketch
